version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://admin:password@mongo:27017/restaurant?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app

volumes:
  mongo-data: